[package]
name = "interceptor"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.4.0"
http = "0.2.9"
http-body = "0.4.5"
pin-project = "1.1.3"
tonic = "0.9.2"
tower-layer = "0.3.2"
tower-service = "0.3.2"

[dev-dependencies]
tokio = {version = "1.0", features = ["rt", "macros"]}
tower = {version = "0.4.7", features = ["full"]}