# Network and HTTP
http = "1.1.0"
http-body = "1.0.0"
tonic = "0.11.0"
lapin = "2.3.1"
mongodb = "2.8.2"
redis = "0.25.3"

# Authentication and Security
argon2 = "0.5.3"
password-hash = "0.5.0"
jwt = "0.16.0"
hmac = "0.12.1"
sha2 = "0.10.8"

# Serialization and Data Formats
prost = "0.12.4"
serde = "1.0.197"
serde_json = "1.0.115"

# Asynchronous Programming
async-trait = "0.1.80"
futures = "0.3.30"
futures-lite = "2.3.0"
tokio = "1.37.0"
tokio-test = "0.4.4"

# Messaging and Queueing
amiquip = "0.4.2"

# Concurrency and Middleware
tonic-async-interceptor = "0.11.1"
tower = "0.4.13"
tower-layer = "0.3.2"
tower-service = "0.3.2"

# Random Number Generation
rand = "0.8.5"

# Binary Data Handling
bytes = "1.6.0"

# Development and Build
protoc-bin-vendored = "3.0.0"
tonic-build = "0.11.0"

# Configuration and Environment
dotenv = "0.15.0"

# Parallelism and Concurrency
pin-project = "1.1.5"