services:
  amqp:
    image: rabbitmq:latest
    env_file:
      - .env.production
    volumes:
      - ./:/data
    ports:
      - '${AMQP_PORT}:${AMQP_PORT}'
    restart: on-failure

  redis:
    image: redis:latest
    env_file:
      - .env.production
    volumes:
      - ./:/data
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    restart: on-failure

  mongo:
    image: mongo:latest
    env_file:
      - .env.production
    volumes:
      - ./:/data
    ports:
      - '${MONGO_PORT}:${MONGO_PORT}'
    restart: on-failure

  account:
    build:
      args:
        SERVICE_NAME: account
    env_file:
      - .env.production
    environment:
      MONGO_HOSTNAME: mongo
    links:
      - mongo
    volumes:
      - ./:/data
    ports:
      - '${ACCOUNT_PORT}:${ACCOUNT_PORT}'
    restart: on-failure

  token:
    build:
      args:
        SERVICE_NAME: token
    env_file:
      - .env.production
    environment:
      REDIS_HOSTNAME: redis
    links:
      - redis
    volumes:
      - ./:/data
    ports:
      - '${TOKEN_PORT}:${TOKEN_PORT}'
    restart: on-failure

  authentication:
    build:
      args:
        SERVICE_NAME: authentication
    env_file:
      - .env.production
    environment:
      ACCOUNT_HOSTNAME: account
      TOKEN_HOSTNAME: token
    links:
      - account
      - token
    volumes:
      - ./:/data
    ports:
      - '${AUTHENTICATION_PORT}:${AUTHENTICATION_PORT}'
    restart: on-failure

  conversation:
    build:
      args:
        SERVICE_NAME: conversation
    env_file:
      - .env.production
    environment:
      AMQP_HOSTNAME: amqp
      MONGO_HOSTNAME: mongo
    links:
      - amqp
      - mongo
    volumes:
      - ./:/data
    ports:
      - '${CONVERSATION_PORT}:${CONVERSATION_PORT}'
    restart: on-failure

  matchmaking:
    build:
      args:
        SERVICE_NAME: matchmaking
    env_file:
      - .env.production
    environment:
      AMQP_HOSTNAME: amqp
      MONGO_HOSTNAME: mongo
      REDIS_HOSTNAME: redis
    links:
      - amqp
      - mongo
      - redis
    volumes:
      - ./:/data
    ports:
      - '${MATCHMAKING_PORT}:${MATCHMAKING_PORT}'
    restart: on-failure

  profile:
    build:
      args:
        SERVICE_NAME: profile
    env_file:
      - .env.production
    environment:
      MONGO_HOSTNAME: mongo
    links:
      - mongo
    volumes:
      - ./:/data
    ports:
      - '${PROFILE_PORT}:${PROFILE_PORT}'
    restart: on-failure

  recommendation:
    build:
      args:
        SERVICE_NAME: recommendation
    env_file:
      - .env.production
    environment:
      AMQP_HOSTNAME: amqp
      MATCHMAKING_HOSTNAME: matchmaking
      REDIS_HOSTNAME: redis
      PROFILE_HOSTNAME: profile
    links:
      - amqp
      - matchmaking
      - redis
      - profile
    volumes:
      - ./:/data
    ports:
      - '${RECOMMENDATION_PORT}:${RECOMMENDATION_PORT}'
    restart: on-failure

  safety:
    build:
      args:
        SERVICE_NAME: safety
    env_file:
      - .env.production
    environment:
      MONGO_HOSTNAME: mongo
    links:
      - mongo
    volumes:
      - ./:/data
    ports:
      - '${SAFETY_PORT}:${SAFETY_PORT}'
    restart: on-failure

  support:
    build:
      args:
        SERVICE_NAME: support
    env_file:
      - .env.production
    environment:
      MONGO_HOSTNAME: mongo
    links:
      - mongo
    volumes:
      - ./:/data
    ports:
      - '${SUPPORT_PORT}:${SUPPORT_PORT}'
    restart: on-failure

  gateway:
    build:
      args:
        SERVICE_NAME: gateway
    env_file:
      - .env.production
    environment:
      AUTHENTICATION_HOSTNAME: authentication
      CONVERSATION_HOSTNAME: conversation
      MATCHMAKING_HOSTNAME: matchmaking
      PROFILE_HOSTNAME: profile
      RECOMMENDATION_HOSTNAME: recommendation
      SAFETY_HOSTNAME: safety
      SUPPORT_HOSTNAME: support
    links:
      - authentication
      - conversation
      - matchmaking
      - profile
      - recommendation
      - safety
      - support
    volumes:
      - ./:/data
    ports:
      - '${GATEWAY_PORT}:${GATEWAY_PORT}'
    restart: on-failure