[package]
name = "amqp"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-lite = { version = "2.3.0" }
lapin = { version = "2.3.1" }
tokio = { version = "1.37.0" }
tokio-test = { version = "0.4.4" }